//temuriylar , savet , jahon, mustaqillik, world  
export const adib = [

    {
        id: 1,
        name: 'Zahiriddin M',
        img: `https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Zahiriddin_Muhammad_Bobur.jpg/220px-Zahiriddin_Muhammad_Bobur.jpg`,
        category: 'temuriylar',
        date: '1483 - 1530',
        books: 45,
        au: 24,
        dis: `Bobur (taxallusi) toliq ismi - Zahiriddin Muhammad ibn Umarshayx Mirzo. U 1483-yil 14-fevral–1530-yil 26-dekabr) — oʻzbek mumtoz adabiyotining yirik vakili, shoir, tarixchi, geograf, davlat arbobi, isteʼdodli sarkarda, boburiylar sulolasi asoschisi, temuriy shoh boʻlgan. Amir Temurning pannevarasi bolgan[2]. Bobur oz davrining buyuk shaxslaridan biri edi. Uning sheʼrlari, ruboiylari oʻz vaqtida va hozir ham sevib oʻqilmoqda. 6 ta xotini boʻlgan. Bibi Muboraka, Mohimbegim, Zaynab Sulton Begim, Oysha Sulton Begim, Maʼsuma Sulton Begim va Soliha Sulton Begim Bu paytda, qisqa muddat ichida Samarqand taxtiga uchinchi hukmdor kelgan edi. Sulton Ahmad Mirzo vafoti (1494-yil iyul) dan keyin taxtga oʻtirgan Sulton Mahmud Mirzo Samarqandda davlatni 5-6 oydan ortiq idora etmadi — qisqa muddatli kasallikdan soʻng 43 yoshida vafot etdi. Uning oʻrniga Buxoroda hokim boʻlgan oʻgʻli Boysungʻur oʻtiradi. 1495—1496-yillarda Bobur Samarqandga ikki marta muvaffaqiyatsiz yurish qiladi. 1497-yil kuzida u Samarqand atrofidagi bir qancha joylarni va 7 oylik qamaldan soʻng Samarqandni egallaydi, Boysungʻur Qunduzga qochadi. Shahar qamal tufayli nihoyatda ogʻir kunlarni boshidan kechirmoqda edi. Hatto ekkulik don ham topish mushkul edi. Bobur qoʻshinni taʼminlashda katta qiyinchiliklarga duch keldi. Navkarlaridan ayrimlari Andijon va Axsi tomon qochib ketadilar. Buning ustiga Andijonda qolgan ayrim beklar Boburdan yuz oʻgirib, uning ukasi Jahongir Mirzo tarafiga oʻtadilar. Andijondan koʻngli notinch boʻlgan va iqtisodiy qiyinchiliklarga uchragan, ayni zamonda ogʻir xastalikni boshidan kechirgan Bobur Samarqandni yuz kun idora etgandan soʻng, uni tark etishga qaror qiladi, ammo Xoʻjandga yetganda Andijon ham qoʻldan ketib, muxoliflar ixtiyoriga oʻtganini eshitadi. Boburning Toshkent hokimi, togʻasi Mahmudxon koʻmagida Andijonni qayta egallashga urinishi natija bermaydi. Bu muvaffaqiyatsizlik Bobur qoʻshiniga salbiy taʼsir etib, koʻpchilik bek, navkarlar (700—800 kishi) Boburni tark etadi. Oʻziga sodiq kishilar (200—300) bilan qolgan Bobur maʼlum muddat Xoʻjandda turgach, Toshkentga — Mahmudxon huzuriga kelib, Andijonni qaytarib olish rejasini tuza boshlaydi. Maʼlum muddat oʻtgach, Bobur Xoʻjandga qaytadi, koʻp oʻtmay, Margʻilonni qoʻlga kiritadi hamda Andijonni egallash tadbirlarini koʻradi. Nihoyat, 2 yildan soʻng (1498-yil iyun) uni qayta qoʻlga kiritadi. Bobur ukasi Jahongir Mirzo bilan sulh tuzib, uning ixtiyorida „Xoʻjand suvining Axsi tarafi viloyatlarini…“ qoldiradi.`
    }
    ,
    {
        id: 2,
        name: 'Amir Temur',
        img: `https://www.creative-tours.uz/wp-content/uploads/2023/07/photo_2023-07-21_14-16-29.jpg`,
        category: 'temuriylar',
        date: '1336 - 1405',
        books: 32,
        au: 17,
        dis: `Temurbek shabon oyining yigirma beshida, hijriy yetti yuz oʻttiz oltinchi yilda (8.04.1336), oʻn ikki hayvonli Turk yilligiga koʻra Sichqon yilida Kesh shahri yaqinidagi Xoʻja Ilgʻor qishlogʻida tulilgan. Ayricha amerikalik tarixchi Beatrice Forbes Manz xonim Temurbekning tugʻilgan yilini oʻn toʻrtinchi yuzyillikning yigirmanchi yillariga toʻgʻri kelishini kabi o'z ikkilanishli qarashlarini oldinga surib keladi va bu shubhalanishiga sabab qilib Temurbekning 1336-yilda tugʻilganligi toʻgʻrisidagi yozuvlar uning davridan keyin yozilganini va uning davriga tegishli bir nechta manbalardagi voqealarda Temurbekning yoshi uning 1320-yillar oxirida tugʻilganini koʻrsatishini aytadi (qarang, Tamerlane and the Symbolism of Sovereignty, B. F. Manz). Biroq birorta tarix kitoblarida Temurbekning tugʻilgan yili 1336-yil emas, balki boshqa yil ekanligi toʻgʻrisida bilgi umuman uchramaydi Temurbek shabon oyining yigirma beshida, hijriy yetti yuz oʻttiz oltinchi yilda (8.04.1336), oʻn ikki hayvonli Turk yilligiga koʻra Sichqon yilida Kesh shahri yaqinidagi Xoʻja Ilgʻor qishlogʻida tulilgan. Ayricha amerikalik tarixchi Beatrice Forbes Manz xonim Temurbekning tugʻilgan yilini oʻn toʻrtinchi yuzyillikning yigirmanchi yillariga toʻgʻri kelishini kabi o'z ikkilanishli qarashlarini oldinga surib keladi va bu shubhalanishiga sabab qilib Temurbekning 1336-yilda tugʻilganligi toʻgʻrisidagi yozuvlar uning davridan keyin yozilganini va uning davriga tegishli bir nechta manbalardagi voqealarda Temurbekning yoshi uning 1320-yillar oxirida tugʻilganini koʻrsatishini aytadi (qarang, Tamerlane and the Symbolism of Sovereignty, B. F. Manz). Biroq birorta tarix kitoblarida Temurbekning tugʻilgan yili 1336-yil emas, balki boshqa yil ekanligi toʻgʻrisida bilgi umuman uchramaydi.

        Otasi Amir Taragʻay (oʻrta chogʻ turkchasida Taragʻay – qoraquyruq qushi) barlos qabilasining beklaridan biri va qabilaning asosiy 5 ta urugʻidan birining yetakchisi edi (qarang, The rise and rule of Tamerlane, B. F. Manz va The Mongol Period B. Spuler). Taragʻaybek Chigʻatoy ulusining taniqli beklaridan biri boʻlib, Kesh viloyatida amirlik qilgan. Amir Taragʻay yillik Ili daryosi boʻyida Xon tomonidan chaqiriladigan yurt beklarining qurultoyiga chaqirilgan va bunday yigʻinlarda qoldirmasdan qatnashgan. Butga topinuvchi oʻlaroq tugʻilgan Taragʻaybek Chigʻatoy ulusi orasida birinchilardan boʻlib islom dinini qabul qilgan. Otasi Barqul Noyondek Tarag'aybek harb va siyosat ishlariga qiziqmagan va asosan islom dinini oʻrganish bilan umrini kechirgan. Temurbek tez-tez qabrini ziyorat qiladigan va keyinchalik qabri ustiga maqbara (1373–1374) qurdirgan Shamsiddin Kulol Taragʻaybekning piri boʻlgan.
        
        .`
    }
    ,
    {
        id: 3,
        name: "Mirzo Ulug'bek",
        img: `https://corp.uzairways.com/sites/default/files/inline-images/1_3.jpg`,
        category: 'temuriylar',
        date: '1394-1449',
        books: 25,
        au: 15,
        dis: `Mirzo Ulugʻbek (toʻliq ismi: Sulton Muhammad ibn Shohrux ibn Temur Ulugʻbek Koʻragon; 1394-yil 22-mart, Sultoniya — 1449-yil 27-oktyabr, Samarqand) — Temuriylar davlatining hukmdori, buyuk astronomi (yulduzshunos) va matematigi. U otasi Shohrux Mirzo davrida Mavarounnahr hokimi va otasi vafot etgach butun Temuriylar imperiyasi sultoni (1447—1449) boʻldi. Ulugʻbek  trigonometriya va sferik geometriya kabi astronomiya bilan bogʻliq matematika sohasidagi ishlari, shuningdek, sanʼat va intellektual faoliyatga umumiy qiziqishlari bilan ajralib turardi.   U besh tilda: turkiy, arab,  fors,  moʻgʻul va oz miqdorda xitoy tillarini bilgan deb taxmin qilinadi.  Uning hukmronligi davrida (avval hokim, keyin toʻgʻridan-toʻgʻri) uning eʼtibori va homiyligi tufayli temuriylar uygʻonish davrining  madaniy choʻqqisiga erishdi. Samarqand hokimligi, otasi Shohrux Mirzo tomonidan Ulugʻbekga berilgan 1447-yilda otasi Shohruxning vafotidan xabar topgan Ulugʻbek Balxga joʻnadi . Bu yerda u oʻzining marhum akasi Boysungʻurning oʻgʻli Alovuddavlaning Hirotda Temuriylar saltanati hukmronligini daʼvo qilganini eshitdi . Binobarin, Ulug‘bek Alouddavlaga qarshi yurish qildi va Murg‘obda jangda u bilan uchrashdi . U oʻz jiyani ustidan gʻalaba qozonib, 1448-yilda Hirotga qarab yurdi. Biroq Alouddavlaning ukasi Abulqosim Bobur Mirzo unga yordamga keldi va Ulugʻbekni magʻlub etdi. Ulugʻbek Balxga chekindi va u yerda uning hokimi, toʻngʻich oʻgʻli Abdullatif Mirzo isyon koʻtarganini bildi. Yana ichki urush boshlandi.  Abdullatif Amudaryo boʻyida otasining qoʻshinini kutib olish uchun qoʻshin toʻpladi . Biroq Ulug‘bek shahardagi notinchlik xabarini eshitib, hech qanday jang bo‘lmasdan turib Samarqandga chekinishga majbur bo‘ladi. Abdullatif tez orada Samarqandga yetib boradi va Ulug‘bek beixtiyor o‘g‘liga taslim bo‘ladi. Abdullatif otasini hibsdan ozod qilib, Makkaga haj qilishiga ruxsat berdi. Biroq, manziliga yetib bormasdan turib otasi va ukasi Abdulazizni ham 1449-yilda qatl qildirdi U Turon hukmdori Amir Temurning nabirasi va Shohrux Mirzoning oʻgʻli edi. Onasi turkiy qabila zodagonlaridan Gavharshod begim edi. U bobosining Eronga yurishi paytida Sultoniya shahrida tugʻilgan. Unga Mirzo Muhammad Taragʻay ismi berildi. Ulugʻbek asli ism emas, balki „Buyuk hukmdor (bek)“ maʼnosini beruvchi taxallus edi. Bolaligida u Yaqin Sharq va Hindistonning katta qismini kezib chiqdi, chunki bobosi bu hududlarda fathlarni kengaytirdi. Temur vafotidan keyin Shohrux imperiya poytaxtini Hirotga (zamonaviy Afgʻonistonda) koʻchirdi. 16 yoshli Ulugʻbek keyinchalik, 1409-yilda Samarqandning hokimi boʻldi. 1411-yilda u butun Movarounnahrning hokimi deb eʼlon qilindi. Ammo, amalda Hirotdagi otasi Shohrux Mirzo hokimiyatiga boʻysungan..`
    },
    {
        id: 4,
        name: "Alisher Navoiy",
        img: `https://static.norma.uz/images/164081_00ff07a7158f6347bd5318831939.jpg`,
        category: 'temuriylar',
        date: '1441-1501',
        books: 50,
        au: 32,
        dis: `Alisher Navoiy (9-fevral 1441-yildan 3-yanvar 1501-yilgacha umr koʻrgan) — oʻzbek va boshqa turkiy xalqlarning shoiri, mutafakkiri va davlat arbobi[1][2][3]. Gʻarbda Chigʻatoy adabiyotining buyuk vakili deb qaraladi.Tarixchi Ali Yazdiy nazariga tushgan, shoir Lutfiy yosh shoir isteʼdodiga yuqori baho bergan, Kamol Turbatiy eʼtirofini qozongan. Sayyid Hasan Ardasher, Pahlavon Muhammad kabi ustozlardan taʼlim olgan, Abdurahmon Jomiy bilan ijodiy hamkorlikda boʻlgan. Navoiy 1469-yilgacha temuriylar orasidagi ichki nizolar sababli Hirotdan yiroqroqda yashagan Alisher Navoiy 1441-yil 9-fevralda Amir Temurning oʻgli Shohruh Mirzo shohligi davrida Hirotda tugʻildi. Zamondoshlari uning haqida koʻpincha „Nizomiddin Mir Alisher“ deb yozadilar. 'Nizomiddin" — din-diyonat nizomi degani boʻlib, donishmand mansab egalariga beriladigan sifat, „mir“ amir demakdir. Uning otasi Gʻiyosiddin Muhammad (uni Gʻiyosiddin Kichkina ham der edilar) temuriylar saroyining amaldorlaridan, xonadonning ishonchli kishilaridan edi. Onasi amirzoda Shayh Abusaid Changning qizi boʻlgan, ismi maʼlum emas. Alisherning bobosi Temurning oʻgʻli Umarshayx bilan emikdosh (koʻkaldosh) boʻlgan ekan.
        Buyuk shoir oʻz asarlarida bu qutlugʻ dargohga yaqinligidan iftixor etishini bayon qiladi. Shuningdek, uning tarjimai holiga oid ayrim lavhalar asarlarida uchraydi. Bu tabarruk zot toʻgʻrisidagi baʼzi maʼlumotlarni esa uning zamondoshlari oʻz kitoblarida beradilar.
        Alisher saroy muhitida yashaganligi uchun alohida tarbiya va nazoratda oʻsdi. Kichiklik chogʻidan sheʼr va musiqaga ishqi tushdi. Olim-u fozillar davrasida boʻldi. Uch-toʻrt yoshlarida davrining mashhur shoiri Qosim Anvorning bir sheʼrini yod aytib, mehmonlarni hayratga soldi. Bir yildan soʻng uni maktabga berdilar. U boʻlajak sulton Husayn Bayqaro bilan birga oʻqidi. Uning zehni va iqtidori haqidagi gaplar esa el orasida tarqalib bordi.
        1447-yilda Shohruh Mirzo vafot etib, temuriy shahzodalar oʻrtasida taxt uchun kurash boshlanadi. Hirot notinch boʻlib qoladi. Alisherlar oilasi Iroqqa yoʻl oladi. Yoʻlda, Taft shahrida Alisher zamonasining mashhur tarixchisi, „Zafarnoma“ning muallifi Sharafiddin Ali Yazdiy bilan uchrashdi 1452-yilda Abulqosim Bobur Mirzo Xuroson taxtiga oʻtiradi, notinchliklar bosiladi. Gʻiyosiddin Muhammad Sabzavorga hokim qilib tayinlanadi. Alisher esa oʻqishini davom ettiradi. Maktab yosh Alisherni sheʼriyat, adabiyot olamiga olib kirdi. Boʻlajak shoir Saʼdiy Sheroziyning „Guliston“. „Boʻston“, asarlarini, Farididdin Attorning „Mantiq ut-tayr“(„Qush mantigʻi“)ni soʻngsiz ishtiyoq bilan oʻqidi. Ayniqsa, qushlar tilidan keltirilgan hikoyatlar va ularning chuqur mazmuni Alisherning oʻy-xayolini tamom egallab oldi:`
    }
    , {
        id: 5,
        name: "Abdulla Qodiriy",
        img: `https://corp.uzairways.com/sites/default/files/inline-images/abq.jpg`,
        category: "savet",
        date: "1894 - 1938",
        books: 4,
        au: 3,
        dis: `Abdulla Qodiriy (asosiy taxalluslari: Qodiriy, Julqunboy) (1894.4.10-Toshkent-1938.10.4) – XX-asr yangi oʻzbek adabiyotining ulkan namoyandasi, oʻzbek romanchiligining asoschisi; 20-yillardagi muhim ijtimoiy-madaniy jarayonlarning faol ishtirokchisi. Bogʻbon oilasida tugʻilgan. Otasi Qodirbobo (1820—1924) xon, beklar qoʻlida sarbozlik qilgan, rus bosqini paytida (1865) Toshkent mudofaasida qatnashgan. Otasi boshidan oʻtgan sarguzashtlar Abdulla Qodiriyning qator asarlari, xususan tarixiy romanlarining yuzaga kelishida muhim rol oʻynagan. Abdulla Qodiriy musulmon maktabida (1904–1906), rus-tuzem maktabida (1908–12), Abulqosim shayx madrasasida (1916–17) taʼlim oldi; Moskvadagi adabiyot kursida (1925-26) oʻqidi. Yoshligidanoq qadimgi Sharq madaniyati va adabiyoti ruhida tarbiya topgan; arab, fors va rus tillarini oʻrgangan. Jahon adabiyotini ixlos bilan mutolaa qilgan. Abdulla Qodiriyning ulkan merosi haligacha kitobxonlar qalbidan joy olmoqda.
        Abdulla Qodiriyning 44 yillik umri, 20 yillik ijtimoiy va ijodiy faoliyat davri keskin kurashlar, taʼqibu tahdidlar ichida oʻtdi. Rostgoʻy adib shoʻro davri haqidagi badiiy asarlarida, publitsistikasida shoʻro voqeligiga xos ziddiyatlarni, siyosatdagi xato va kamchiliklarni xolis turib koʻrsatishga jazm etdi. Ammo uning bu urinishlari birin-ketin zarbaga uchray boshladi. 1926-yil „Mushtum“da bosilgan „Yigʻindi gaplar“ hajviyasidagi tanqidiy mulohazalari uchun „aksilinqilobiy harakat qilganlik“da ayblanib qamoqqa olinadi, turli boʻxtonlar bilan sudlanadi. Sudda u mardona turib oʻz shaʼnini himoya qiladi. „Obid ketmon“ qissasi ham shoʻro mafkurachilariga maʼqul kelmaydi, keskin tanqidga uchraydi; „ideologik buzuqliklar va xatolar“ga toʻla, „siyosiy tutruqsiz“ asar sifatida baholanadi. Yozuvchining tarixiy romanlarining esa asosiy mavzusi – millat taqdiri, birligi, el-yurt qaygʻusi, mustaqilligi, shaxs erki, ijtimoiy adolat uchun kurash gʻoyalari bilan yoʻgʻrilganligi tufayli ham hukmron mafkuraga zid asarlar boʻlib chiqdi. Millat ruhini yorqin aks ettirgan, xalqning, oʻzga millat kitobxonlarining sevimli asarlariga aylangan bu romanlar shoʻro davri siyosati uchun zararli kitoblar sifatida bot-bot qoralandi. 30-yillar oʻrtalariga kelib, bu mashʼum kampaniya avjiga chiqdi. Gʻofir Gʻulom, Abdulla Qahhor, Uygʻun kabi shogirdlarining "donos"lari ortidan Abdulla Qodiriy 1937-yil 31-dekabr kuni xibsga olindi. 9 oylik qamoqdagi soʻroq-tergov, qiynoq, xoʻrlikdan soʻng Choʻlpon, Fitrat kabi maslakdoshlari bilan birga qatl etildi. Qodiriy xibsga olingach, asarlari „zararli“ sanalib oʻtda yoqildi, kutubxonalardan yoʻqotildi, ularni oʻqish taʼqiqlandi.`
    },
    {
        id: 6,
        name: "Abdulhamid Cho'lpon",
        img: `https://upload.wikimedia.org/wikipedia/commons/9/9c/Abdulhamid_Cholpon.jpg`,
        category: "savet",
        date: "1898 - 1938",
        books: 9,
        au: 9,
        dis: `Choʻlpon (asl ism-sharifi Abdulhamid Sulaymon oʻgʻli Yunusov 1897-yil, Andijon — 1938.4.10, Toshkent) — shoir, yozuvchi, dramaturg , tarjimon, tanqidchi va jamoat arbobi. Dastlab, madrasada (1908-1912), soʻngra rus-tuzem maktabida (1912-1914) oʻqigan. Sharq mumtoz shoirlari asarlarini mutolaa qilish va jadid matbuotini kuzatish yoʻli bilan adabiy, ijtimoiy-siyosiy bilimini oshirgan.
        1914-yil Toshkentga kelib, „Sadoi Turkiston“ gazetasi bilan hamkorlik qilgan. „Yangi Sharq“, „Ishtirokiyun“ (1920-yildan „Qizil bayroq“, 1922-yildan „Turkiston“) gazetasida adabiy xodim (1919-1923), Xalq maorif komissarligi qoshidagi Ilmiy kengash (1921-yildan Oʻlka oʻzbek bilim hayʼati, 1922-yildan Ilmiy hayʼat)da rais (1920-1923), „Buxoro axboroti“ gazetasida muharrir (1921-1922), „Turon“ teatrida direktor (1921; 1922-1923), „Mushtum“ jurnali va „Darxon“ gazetasida texnik muharrir, adabiy xodim (1922-1923), Oʻzbek drama studiyasi (Moskva, 1924-1927) va Oʻzbek davlat drama teatrida adabiy emakdosh (1927-1931), SSSR XKS va Sharq xalqlari markaziy nashriyotida tarjimon (Moskva, 1931-1934), „Mushtum“ va „Guliston“ jurnallari hamda „Teatru“ gazetasida adabiy xodim (jamoatchilik asosida, 1935-1937). 1938-yilda 4-oktabrda Bozsuv boʻyida qatl qilinadi.
        Jadidlarga qarshi boshlangan kampaniya Choʻlponni ham chetlab oʻtmaydi. Taʼqib va tazyiqlarga qaramay, u qizgʻin ijodiy faoliyat bilan shugʻullanadi. 30-yillarning boshida yana Moskvaga ketgan va SSSR Markaziy Ijroiya Komitetida tarjimon boʻlib ishlagan. Choʻlpon 1937-yil 14-iyulda qamoqqa olinadi va 1938-yil 4-oktabrda Toshkentda Boʻzsuv boʻyida qatl etiladi 1917-yil Fevral inqilobining roʻy berishi taraqqiyparvar ziyolilar dunyoqarashini oʻzgartirib yubordi. Ular, shu jumladan, Choʻlpon mustaqillik uchun kurash endi targʻibiy-tashviqiy davridan amaliy faoliyat bosqichiga oʻtganini angladilar. Choʻlpon Turkiston muxtoriyati hukumatining barpo etilishida faol ishtirok etib, muxtoriyatni sharaflovchi „Ozod turk bayrami“ sheʼrini yozdi va bu sheʼr oʻzbek davlatchiligi tarixida ilk madhiya boʻldi. Shu davrda Turkistondagi koʻp millatli ziyolilar oʻrtasida federalizm gʻoyasi keng tarqalgani sababli Choʻlpon ayni paytda Z.Validiy bilan birga Orenburgga borib, Boshqirdiston muxtoriyat hukumatining tashkil etilishida ham ishtirok etdi. Federalistlarning fikrlariga koʻra, Turkiston va Volga boʻyidagi turkiy xalqlar oʻz muxtoriyat hukumatlarini barpo etganlaridagina bu hukumatlarning bolsheviklar tomonidan tan olinishi va birgalikda himoyalanishi mumkin edi.
        Muxtoriyat tugatildi.`
    },



    {
        id: 13,
        name: 'Tohir Malik',
        img: `https://upload.wikimedia.org/wikipedia/en/2/2f/Tohir_Malik.jpg`,
        category: 'mustaqillik',
        date: '1946-2019',
        books: 52,
        au: 30,
        dis: `Tohir Malik oʻnga yaqin radiopʼesalar, hujjatli film ssenariylari, badialar muallifi. Badiiy tarjima sohasida ham xizmat qilgan.
        Tohir Malik 1966-yildan eʼtiboran matbuot sohasida ishlagan. Lenin uchquni (Hozir Tong yulduzi deb nomlanadi), Oʻzbekiston radiosida, Gʻafur gʻulom nomidagi va „Choʻlpon“ nashriyotlarida, „Sharq yulduzi“, „Yoshlik“ jurnallarida faoliyat yuritgan. U ijodiiy faoliyati davomida hayotni, insonlar tabiatini atroflicha oʻrgana boshlaydi. Yozuvchi insonlarni, ularning ichki kechinmalarini, ruhiyatlarini sinchiklab oʻrganadi va kitobxonni ham mana shu ruhiyat olamiga olib kiradi. Uni shu holga solgan sabablarni tahlil qilishga va xulosa chiqarishga yoʻnaltiradi. Yozuvchi yaratgan asarlari asosida koʻplab tele va baʼdiy filmlar yaratilgan. Asarlarida turli qiyofadagi zamondoshlarimizning obrazlari yorqin lavhalarda katta mahorat bilan aks etgan, muhim maʼnaviyaxloqiy muammolar koʻtarilgan[4]. Rus yozuvchisi F.M. Dostoyevskiyning Maʼsuma qissasini, shuningdek, jahon adabiyoti namoyandalarining ayrim asarlarini oʻzbek tiliga tarjima qilgan. 1961–1964-yillarda quruvchi, 1965–1966-yillarda maktabda oʻqituvchi boʻlib ishlagan. Lenin uchquni gazetasi, 1975–1978-yillarda Guliston nashriyotida, 1981–1982-yillarda Gʻafur Gʻulom nomidagi nashriyotda muharrir, 1982–1985-yillarda Sharq yulduzi jurnalida, 1985–1987-yillarda Choʻlpon nashriyotida bosh muharrir, 1989–91-yillarda „Yoshlik“ jurnalida adabiy xodim, masʼul kotib, bosh muharrir, Oʻzbekiston yozuvchilari uyushmasida 1988–90-yillar davomida kotib boʻlib faoliyat olib borgan Birinchi yirik asari — „Hikmat afandining oʻlimi“ (1972). „Zaharli gʻubor“ (1974), „Falak“ (1975), „Somon yoʻli elchilari“ (1978), „Chorrahada qolgan odamlar“ (1982), „Bir koʻcha, bir kecha“ (1983), „Alvido, bolalik“ (1989), „Soʻnggi oʻq“ (1990), „Ov“ (1995) kabi ilmiy-fantastik, sarguzasht qissalari mashhur. „Soʻnggi oʻq“ qissasi asosida 7 qismli telefilm (1994) yaratilgan. „Qaldirgʻoch“ (1987) epik asari Abdulla Avloniy taqdiri misolida 20-yillar oʻzbek ziyolilarining shakllanishi haqida bahs yuritadi. „Mehmon tuygʻular“ (2003) nomli xotira, yodnoma, adabiy maqolalar toʻplamida adabiy jarayondagi muammolar aks etgan. Tohir Malikning yozuvchi Mirzakalon Ismoiliy ijodiy faoliyatini yorituvchi „Yozuvchining baxti va baxtsizligi“ (1988), Asqad Muxtor ijodini taxlil etuvchi „Sobir“ (2003), Oʻlmas Umarbekov ijodiga bagʻishlangan „Qiyomat qarz“ (2002) hamda Abdulla Qodiriy romanlari taxlil etilgan „Ibrat maktabi“ (1993) badialari xam bor. Tohir Malik xujjatli kino sohasida xam faoliyat koʻrsatgan. Uning „Amir Temur davri adabiyoti“ (1998), „Varaxsha“ (1999), „Unvoni inson“ (1999), „Sohilsiz dengiz“ (2000), „Zulmat saltanati“, (2001), „Moshtabib“ (2002) siyenariylari asosida hujjatli filmlar ishlangan.`
    },
    {
        id: 14,
        name: 'Xudoyberdi Toʻxtaboyev',
        img: `https://aniq.uz/photos/news/zigAwnaRcIutTa9.jpeg`,
        category: 'mustaqillik',
        date: '1932-2021',
        books: 30,
        au: 30,
        dis: `Xudoyberdi Toʻxtaboyev (1932-yil 17-dekabr, Oʻzbekiston tumani–2021-yil 21-mart[1]) — Oʻzbekiston xalq yozuvchisi (1991). Oʻzbekistonda xizmat koʻrsatgan madaniyat xodimi (1982). Qoʻqon pedagogika bilim yurtini (1949), Oʻrta Osiyo universitetini tugatgan (1955). Oʻrta maktabda oʻqituvchi va direktor (1955–1958), „Toshkent haqiqati“ gazetasida adabiy xodim, boʻlim mudiri (1958–1962), „Sovet Oʻzbekistoni“ (1962–1970) gazetasida, „Guliston“ jurnalida (1970–1972), „Yosh gvardiya“ nashriyotida (1972) boʻlim mudiri va bosh muharrir oʻrinbosari (1974–1976), „Gulxan“, „Yosh kuch“ jurnallarida bosh muharrir (1977–1980), „Oltin meros“ xalqaro xayriya jamgʻarmasi boshqaruvi raisi (1980–1998). Dastlab jurnalist sifatida tanilgan, felyetonlar yozgan. Badiiy ijod bilan XX asr 50-yillarida shugʻullana boshlagan. Ilk hikoyalar toʻplami — „Shoshqaloq“ (1961). „Felyetondan keyin“ (1962), „Sir ochildi“ (1963), „Sehrli qalpoqcha“ (1964) singari qissalari, „Muhabbat qoʻshigʻi“ (1967), „Jonginam, shartingni ayt“ (1969), „Konizar yulduzlari“ (1978), „Omonboy bilan Davronboy sarguzashti“ (1974) va boshqa asarlar muallifi. „Sariq devni minib“ romani (1968) yozuvchiga katta shuhrat keltirgan. Shundan keyin „Sariq devning oʻlimi“ (1973), „Besh bolali yigitcha“ (1976), „Qasoskorning oltin boshi“ (1981), „Yillar va yoʻllar“ (1983), „Shirin qovunlar mamlakati“ (1986), „Mungli koʻzlar“ (1988), „Jannati odamlar“ (1996) romanlari nashr etildi. Xudoyberdi Toʻxtaboyev asarlari yumorga boyligi, bolalar hayoti, ularning oʻziga xos tabiati, xususiyatlari, ruhiy kechinmalari nihoyatda jonli, qiziqarli va bolalarbop yoʻsinda mahorat bilan tasvirlanishi jihatidan ajralib turadi. Xudoyberdi Toʻxtaboyev oʻzbek bolalar adabiyotini jahon miqyosiga olib chiqqan ijodkorlardan biridir. Asarlari rus, ingliz, fransuz, nemis tillariga tarjima qilinib, 28ta mamlakatida nashr etilgan. Hamza nomidagi Oʻzbekiston Davlat mukofoti laureati (1989)  „Yosh kuch“ jurnallarida bosh muharrir (1977–1980), „Oltin meros“ xalqaro xayriya jamgʻarmasi boshqaruvi raisi (1980–1998). Dastlab jurnalist sifatida tanilgan, felyetonlar yozgan. Badiiy ijod bilan XX asr 50-yillarida shugʻullana boshlagan. Ilk hikoyalar toʻplami — „Shoshqaloq“ (1961). „Felyetondan keyin“ (1962), „Sir ochildi“ (1963), „Sehrli qalpoqcha“ (1964) singari qissalari, „Muhabbat qoʻshigʻi“ (1967), „Jonginam, shartingni ayt“ (1969), „Konizar yulduzlari“ (1978), „Omonboy bilan Davronboy sarguzashti“ (1974) va boshqa asarlar muallifi. „Sariq devni minib“ romani (1968) yozuvchiga katta shuhrat keltirgan. Shundan keyin „Sariq devning oʻlimi“ (1973), „Besh bolali yigitcha“ (1976), „Qasoskorning oltin boshi“ (1981), „Yillar va yoʻllar“ (1983), „Shirin qovunlar mamlakati“ (1986), „Mungli koʻzlar“ (1988), „Jannati odamlar“ (1996) romanlari nashr etildi. Xudoyberdi Toʻxtaboyev asarlari yumorga boyligi, bolalar hayoti, ularning oʻziga xos tabiati, xususiyatlari, ruhiy.
`
    }
]
