// badiiy, tarixi, ilmiy, comediy, fantastik, ertak
export const books = [
    {
        id: 1,
        adibId: 1,
        title: 'Yolgon',
        price: '230000',
        category: 'badiiy',
        rating: 5,
        author: 'Шайх Муҳаммад Содиқ Муҳаммад Юсуф',
        img: `https://hilolnashr.uz/image/cache/catalog/MSMY/yolgon-web-500x500.jpg`,
        pages: 80,
        date: '2021',
        nash: 'hilol-nashr',
        el: 'pdf, docx',
        au: '3:30'

    },
    {
        id: 2,
        adibId: 1,
        title: 'Lissabondagi tun',
        price: '39000',
        category: 'tarixi',
        rating: 5,
        author: 'Эрих Мария Ремарк',
        img: `https://assets.asaxiy.uz/product/items/desktop/0489ae7ac2a276f3eaa4d73714a3dc282023092916310462320IFwgHwLngI.jpg`,
        pages: 312,
        date: '2020',
        nash: 'assaxiy',
        el: 'pdf, docx',
        au: '5:50'
    }
    ,
    {
        id: 11,
        adibId: 3,
        title: 'Maqsud Shayxzoda',
        price: '70000',
        category: 'badiiy',
        rating: 4.0,
        author: "Mirzo Ulug'bek",
        img: `https://kitobxon.com/img_knigi/5518.jpg`,
        pages: 250,
        date: '1483',
        nash: 'kitobxon',
        el: 'pdf, docx',
        au: '9:30'
    }
    ,
    {
        id: 12,
        adibId: 3,
        title: "To'rt Ulus",
        price: '30000',
        category: 'badiiy',
        rating: 2.0,
        author: "Mirzo Ulug'bek",
        img: `https://assets.asaxiy.uz/product/items/desktop/5e15c15f10368.jpg.webp`,
        pages: 470,
        date: '1510',
        nash: 'kitobxon',
        el: 'pdf, docx',
        au: '20:50'
    }
    ,
    {
        id: 13,
        adibId: 3,
        title: 'Ulugbek Xazinasi',
        price: '25000',
        category: 'badiiy',
        rating: 6.0,
        author: "Mirzo Ulug'bek",
        img: `https://kitobxon.com/img_knigi/3539.jpg`,
        pages: 700,
        date: '1513',
        nash: 'kitobxon',
        el: 'pdf, docx',
        au: '30:30'
    }
    ,
    {
        id: 14,
        adibId: 3,
        title: 'Muhammad Taragay',
        price: '80000',
        category: 'badiiy',
        rating: 4.2,
        author: "Mirzo Ulug'bek",
        img: `https://kitobxon.com/img_knigi/3326.jpg`,
        pages: 210,
        date: '1483',
        nash: 'kitobxon',
        el: 'pdf, docx',
        au: '11:30'
    }
    ,
    {
        id: 15,
        adibId: 3,
        title: 'Mominnning Meroji',
        price: '15000',
        category: 'badiiy',
        rating: 4.9,
        author: "Mirzo Ulug'bek",
        img: `https://kitoblardunyosi.uz/image/cache/catalog/001-Kitoblar/001_hilol_nashr/001_diniy/muminning-meroji-kiril-web-250x400w.jpg`,
        pages: 210,
        date: '1515',
        nash: 'kitobxon',
        el: 'pdf, docx',
        au: '9:30'
    }
    ,
    {
        id: 16,
        adibId: 4,
        title: 'XAMSA',
        price: '50000',
        category: 'badiiy',
        rating: 5.0,
        author: 'Alisher Navoiy',
        img: `https://assets.asaxiy.uz/product/items/desktop/5e15bc073a51a.jpg.webp`,
        pages: 500,
        date: '1483',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '30:30'

    },
    {
        id: 17,
        adibId: 4,
        title: 'Hayrat Ul Abror',
        price: '80000',
        category: 'badiiy',
        rating: 4.7,
        author: 'Alisher Navoiy',
        img: `https://assets.asaxiy.uz/product/main_image/desktop//650fed3a35e47.jpg.webp`,
        pages: 450,
        date: '1483',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '15:30'
    }
    ,
    {
        id: 18,
        adibId: 4,
        title: 'Farxod Va Shirin',
        price: '100000',
        category: 'badiiy',
        rating: 4.0,
        author: 'Alisher Navoiy',
        img: `https://kitobxon.com/img_knigi/s1960.jpg`,
        pages: 650,
        date: '1483',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '15:30'
    }
    ,
    {
        id: 19,
        adibId: 4,
        title: 'MUXOKAMAT',
        price: '56000',
        category: 'badiiy',
        rating: 3.0,
        author: 'Alisher Navoiy',
        img: `https://kitobxon.com/img_knigi/1135.jpg`,
        pages: 300,
        date: '1483',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '10:30'
    }
    ,
    {
        id: 20,
        adibId: 4,
        title: 'Lison Ul Tayir',
        price: '100000',
        category: 'badiiy',
        rating: 4.0,
        author: 'Alisher Navoiy',
        img: `https://kitobxon.com/img_knigi/6832.jpg`,
        pages: 250,
        date: '1483',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '8:30'
    },
    {
        id: 17,
        adibId: 4,
        title: 'Hayrat Ul Abror',
        price: '80000',
        category: 'badiiy',
        rating: 4.7,
        author: 'Alisher Navoiy',
        img: `https://assets.asaxiy.uz/product/main_image/desktop//650fed3a35e47.jpg.webp`,
        pages: 450,
        date: '1483',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '15:30'
    }
    ,
    {
        id: 18,
        adibId: 4,
        title: 'Farxod Va Shirin',
        price: '100000',
        category: 'badiiy',
        rating: 4.0,
        author: 'Alisher Navoiy',
        img: `https://kitobxon.com/img_knigi/s1960.jpg`,
        pages: 650,
        date: '1483',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '15:30'
    }
    ,
    {
        id: 19,
        adibId: 4,
        title: 'MUXOKAMAT',
        price: '56000',
        category: 'badiiy',
        rating: 3.0,
        author: 'Alisher Navoiy',
        img: `https://kitobxon.com/img_knigi/1135.jpg`,
        pages: 300,
        date: '1483',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '10:30'
    }
    ,
    {
        id: 20,
        adibId: 4,
        title: 'Lison Ul Tayir',
        price: '100000',
        category: 'badiiy',
        rating: 4.0,
        author: 'Alisher Navoiy',
        img: `https://kitobxon.com/img_knigi/6832.jpg`,
        pages: 250,
        date: '1483',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '8:30'
    }
    ,
    {
        id: 21,
        adibId: 5,
        title: 'Mehrobdan Chayon',
        price: '29000',
        category: 'badiiy',
        rating: 1,
        author: "Abdulla Qodiriy",
        img: `https://assets.asaxiy.uz/product/main_image/desktop//62e3f0cfd0ab5.jpg.webp`, //
        pages: 320,
        date: '2019',
        nash: 'Ilm-Ziyo-Zakovat',
        el: 'pdf',
        au: '6:15'
    },
    {
        id: 22,
        adibId: 5,
        title: "O'tgan kunlar",
        price: '35000',
        category: 'badiiy',
        rating: 5,
        author: "Abdulla Qodiriy",
        img: `https://assets.asaxiy.uz/product/items/desktop/94aafc73fc9eb3547000f0c2e5b6a4082021042316305750466SItesVCq86.jpg.webp`, //
        pages: 464,
        date: '2019',
        nash: 'Yangi Asr Avlodi',
        el: 'pdf',
        au: '8:20'
    },
    {
        id: 23,
        adibId: 5,
        title: "Jinlar Bazmi",
        price: '30000',
        category: 'badiiy',
        rating: 5,
        author: "Abdulla Qodiriy",
        img: `https://lh6.googleusercontent.com/proxy/paJfv4RdfEGwFORhLQBjc64lYb15vTxpsCVyitMbIXDGHjfuYvvASSbYVPii_kVDjrdK3cUZHsgkuB21NSdZY9p2KP4sRCL_FwNYeOFK7u7Bpy26wGUgCxJFIueANpPzN_10rlf6CQ`, //
        pages: 128,
        date: '2023',
        nash: 'Zabarjad',
        el: 'pdf',
        au: '5:40'
    },
    {
        id: 24,
        adibId: 5,
        title: "Скорпион из Алтаря",
        price: '27000',
        category: 'badiiy',
        rating: 5,
        author: "Abdulla Qodiriy",
        img: `https://xs.uz/upload/post/2019/10/08/3b257e6794ed071b2485eab6398e946e1008.jpg`, //
        pages: 208,
        date: '2019',
        nash: 'Zamin Nashr',
        el: 'pdf',
        au: '13:10'
    },
    {
        id: 26,
        adibId: 6,
        title: 'Kecha va Kunduz',
        price: '39000',
        category: 'roman',
        rating: 5,
        author: "Abdulhamid Cho'lpon",
        img: `https://backend.book.uz/user-api/img/img-file-4bfd6c9a5706126fcf4d6f535262c976.jpg`, //
        pages: 320,
        date: '2019',
        nash: 'Ilm-Ziyo-Zakovat',
        el: 'pdf',
        au: '10:16'
    },
    {
        id: 27,
        adibId: 6,
        title: "Buloqlar Quchog'ida",
        price: '25000',
        category: 'badiiy',
        rating: 5,
        author: "Abdulhamid Cho'lpon",
        img: `https://assets.asaxiy.uz/product/main_image/desktop//64591f6e83538.jpg.webp`, //
        pages: 128,
        date: '2023',
        nash: 'Zabarjad',
        el: 'pdf',
        au: '6:10'
    },
    {
        id: 28,
        adibId: 6,
        title: "Qor qo'ynida lola",
        price: '19000',
        category: 'badiiy',
        rating: 5,
        author: "Abdulhamid Cho'lpon",
        img: `https://lh5.googleusercontent.com/proxy/-tgdjxdypqA3nxOoUOTwrFbMTStAWGmOQnC8Q5pWodWKyYhb7vG8aSXxFGNZj9S2zJGNsk8cVQP4wYK1_9WWTGP27Fcafa0QmdI_KyJ_EYXsxVc`, //
        pages: 128,
        date: '2024',
        nash: 'Ziyo Nashr',
        el: 'pdf',
        au: '6:10'
    },
    {
        id: 29,
        adibId: 6,
        title: "Ko'klam Ruhi",
        price: '25000',
        category: 'badiiy',
        rating: 5,
        author: "Abdulhamid Cho'lpon",
        img: `https://backend.book.uz/user-api/img/img-file-2610dd1075c7ec891a84fa02f0ff3bfa.jpg`, //
        pages: 176,
        date: '2019',
        nash: 'Yoshlar',
        el: 'pdf',
        au: '7:15'
    }
    ,
    {
        id: 51,
        adibId: 11,
        title: 'Nine Stories',
        price: '35000',
        category: 'badiiy',
        rating: 4.3,
        author: 'Jerome David Salinger',
        img: `https://m.media-amazon.com/images/I/71c+10EvbWL._AC_UF1000,1000_QL80_.jpg`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'

    },
    {
        id: 52,
        adibId: 11,
        title: 'Franny',
        price: '35000',
        category: 'comediy',
        rating: 4.3,
        author: 'Jerome David Salinger',
        img: `https://m.media-amazon.com/images/I/81sxuJFFsbL._AC_UF1000,1000_QL80_.jpg`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'

    },
    {
        id: 53,
        adibId: 11,
        title: 'Three Stories',
        price: '35000',
        category: 'tarixi',
        rating: 4.3,
        author: 'Jerome David Salinger',
        img: `https://cdn.kobo.com/book-images/40fd20eb-1e3c-4374-abd1-beaa34341f4c/353/569/90/False/three-early-stories-illustrated.jpg`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'

    },
    {
        id: 54,
        adibId: 11,
        title: 'Three Man in a Boat',
        price: '35000',
        category: 'fantastik',
        rating: 4.3,
        author: 'Jerome David Salinger',
        img: `https://m.media-amazon.com/images/I/61mgffNDcJL.jpg`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'

    },
    {
        id: 55,
        adibId: 11,
        title: 'Catcher',
        price: '35000',
        category: 'ertak',
        rating: 4.3,
        author: 'Jerome David Salinger',
        img: `https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXP-OfMOW65a-ITftol-FmehdXldeQp5N2ObWUJYNYRg&s`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'

    },
    {
        id: 56,
        adibId: 12,
        title: 'Ertaklar',
        price: '35000',
        category: 'ertak',
        rating: 4.3,
        author: 'Sergey Timofeevich Aksakov',
        img: `https://img4.labirint.ru/rc/4bdd06b0624caf2b5a93c5ed49a92af0/363x561q80/books48/470102/cover.jpg?1563802605`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'
    },
    {
        id: 57,
        adibId: 12,
        title: 'Oilavi',
        price: '35000',
        category: 'ertak',
        rating: 4.3,
        author: 'Sergey Timofeevich Aksakov',
        img: `https://m.media-amazon.com/images/I/415CQ30oyhL.jpg`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'
    },
    {
        id: 58,
        adibId: 12,
        title: 'Gullar',
        price: '35000',
        category: 'fantastik',
        rating: 4.3,
        author: 'Sergey Timofeevich Aksakov',
        img: `https://images.uzum.uz/ci9unnd6sfhndlboqtu0/original.jpg`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'
    },
    {
        id: 59,
        adibId: 12,
        title: 'Yoshlik vakti',
        price: '35000',
        category: 'fantastik',
        rating: 4.3,
        author: 'Sergey Timofeevich Aksakov',
        img: `https://s1.livelib.ru/boocover/1002871632/200x305/2f03/boocover.jpg`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'
    }
    ,
    {
        id: 60,
        adibId: 12,
        title: 'Aksakov',
        price: '35000',
        category: 'badiiy',
        rating: 4.3,
        author: 'Sergey Timofeevich Aksakov',
        img: `https://sun9-16.userapi.com/impg/LYeETTTDwih2iqziLPff8S-UVN5nwyHSPm_BJQ/rJo35j_zgfo.jpg?size=647x1080&quality=96&sign=3f42c2676e6c2df8f2e10f5e85ce6b12&type=album`,
        pages: 300,
        date: '2021',
        nash: 'hilol',
        el: 'pdf, docx',
        au: '6:30'
    },
]